# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c23a8f270cc78a855ef081895b05b836cd37c8ecc65add4ca97581f3a619925bc725cc7909a6cdd0cb14bd22784d4cd14b1c44acbf92ffcdeaa9c61db48f4b

test:
  secret_key_base: f26b7cbb24cb26de79712a90defd3c05697da3dbc538f310265afc0a9ce3762d030aa90f8e532bf856c2747a495d6d8d9be01d7bfaf1b92c8051019480f7b173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
